/* Do not edit this file manually.
   This file is autogenerated by windmc.  */

//
//  The values are 32 bit layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      C    - is the Customer code flag
//
//      R    - is a reserved bit
//
//      Code - is the facility's status code
//
//      Sev  - is the severity code
//
//           Informational - 00
#define INFORMATIONAL_EVENT 0x0
//           Success - 00
//           Warning - 01
#define WARNING_EVENT 0x1
//           Error - 02
#define ERROR_EVENT 0x2
//
//      Facility - is the facility code
//
//           Service - 0000
#define FACILITY_SERVICE 0x0
//           System - 00ff
//           Application - 0fff
//

 // The following are message definitions.
//
// MessageId: NVMDIMM_INFORMATIONAL
//
#define NVMDIMM_INFORMATIONAL (DWORD) 0x0

//
// MessageId: NVMDIMM_WARNING
//
#define NVMDIMM_WARNING (DWORD) 0x40000001

//
// MessageId: NVMDIMM_ERROR
//
#define NVMDIMM_ERROR (DWORD) 0x80000002

 // A message file must end with a period on its own line
 // followed by a blank line.
